pipeline {
    agent any

    tools{
        go '1.21'
    }

    stages {
        stage('Deploy') {
            steps{
                sshPublisher(
                    publishers:[sshPublisherDesc(configName: 'ec2-54-234-185-179',
                    transfers:
                    [sshTransfer(cleanRemote: false,
                    excludes: '',
                    execCommand: '',
                    execTimeout: 120000,
                    flatten: false,
                    makeEmptyDirs: false,
                    noDefaultExcludes: false,
                    patternSeparator: '[, ]+',
                    remoteDirectory: 'myblog/templates',
                    remoteDirectorySDF: false,
                    removePrefix: '',
                    sourceFiles: '**/')],
                    usePromotionTimestamp: false,
                    useWorkspaceInPromotion: false,
                    verbose: true)]
                )
            }
        }
    }
}